# Generated by Django 4.2.16 on 2026-03-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cookie_consent",
            field=models.JSONField(
                blank=True, default=dict, help_text="Cookie consent preferences"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cookie_consent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
