# Generated by Django 4.2.16 on 2026-04-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MaxValueValidator, MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0023_straincomment"),
        ("users", "0002_customuser_cookie_consent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumptionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strain_name_text", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, max_length=5000)),
                (
                    "mood_before",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[MinValueValidator(1), MaxValueValidator(5)],
                    ),
                ),
                (
                    "mood_after",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[MinValueValidator(1), MaxValueValidator(5)],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("smoke", "Smoke"),
                            ("vape", "Vape"),
                            ("edible", "Edible"),
                            ("tincture", "Tincture"),
                            ("topical", "Topical"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumption_notes",
                        to="strains.strain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="cons_note_user_date_idx"
                    ),
                ],
            },
        ),
    ]
