# Generated by Django 4.2 on 2024-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_location_options_alter_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(choices=[('mx', 'Mexico'), ('es', 'Spain'), ('ar', 'Argentina'), ('co', 'Colombia'), ('cl', 'Chile'), ('us', 'United States'), ('pe', 'Peru'), ('uy', 'Uruguay')], default='es', max_length=4),
        ),
    ]
