# Generated by Django 4.2 on 2024-08-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('store', 'Store'), ('dispensary', 'Dispensary')], default='store', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
