# Generated by Django 4.2.16 on 2025-08-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatFeedback',
        ),
    ]
