# Generated by Django 4.2 on 2025-08-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_bot", "0002_remove_chat_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="language",
            field=models.CharField(
                blank=True,
                help_text="Detected language (es/en)",
                max_length=2,
                null=True,
            ),
        ),
    ]
