# Generated by Django 4.2.16 on 2026-01-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_bot", "0003_chatsession_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True),
                ),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("window_start", models.DateTimeField(auto_now_add=True)),
                ("last_exceeded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Chat Rate Limit",
                "verbose_name_plural": "Chat Rate Limits",
                "ordering": ["-window_start"],
            },
        ),
    ]
