# Generated by Django 4.2 on 2026-04-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_bot', '0005_chatmessage_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRateLimitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('last_exceeded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rate_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat User Rate Limit',
                'verbose_name_plural': 'Chat User Rate Limits',
                'ordering': ['-window_start'],
            },
        ),
    ]
