# Generated by Django 4.2 on 2023-05-01 14:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0003_alter_article_text_content_alter_strain_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='strain',
            name='text_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
