# Generated by Django 4.2 on 2023-06-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0004_alter_article_text_content_alter_strain_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strain',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
