# Generated by Django 4.2 on 2023-06-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0005_strain_main_strain_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='thc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
