# Generated by Django 4.2 on 2023-07-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0006_alter_strain_thc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
