# Generated by Django 4.2 on 2023-07-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0007_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='cbd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='cbg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='thc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
