# Generated by Django 4.2 on 2023-08-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0008_alter_strain_cbd_alter_strain_cbg_alter_strain_thc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='terpenes',
        ),
        migrations.AddField(
            model_name='strain',
            name='dominant_terpene',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominant_in_strains', to='strains.terpene'),
        ),
        migrations.AddField(
            model_name='strain',
            name='other_terpenes',
            field=models.ManyToManyField(blank=True, related_name='in_strains', to='strains.terpene'),
        ),
        migrations.AddField(
            model_name='terpene',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
