# Generated by Django 4.2 on 2023-08-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0009_remove_strain_terpenes_strain_dominant_terpene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
