# Generated by Django 4.2 on 2023-08-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0010_strain_is_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='dominant_terpene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominant_in_strains', to='strains.terpene'),
        ),
    ]
