# Generated by Django 4.2 on 2023-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0011_alter_strain_dominant_terpene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
