# Generated by Django 4.2.16 on 2025-10-09 15:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0014_article_h3_headings'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='last_translated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful translation', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_content_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_content_es',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='translation_error',
            field=models.TextField(blank=True, help_text='Error message if translation failed', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='translation_source_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of English content when last translated', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='translation_status',
            field=models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('outdated', 'Outdated'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='feeling',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='feeling',
            name='name_es',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='flavor',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='flavor',
            name='name_es',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='helpswith',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='helpswith',
            name='name_es',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='negative',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='negative',
            name='name_es',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='description_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='img_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='img_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='keywords_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='last_translated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful translation', null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='text_content_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='text_content_es',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='translation_error',
            field=models.TextField(blank=True, help_text='Error message if translation failed', null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='translation_source_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of English content when last translated', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='translation_status',
            field=models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('outdated', 'Outdated'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='terpene',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terpene',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terpene',
            name='last_translated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful translation', null=True),
        ),
        migrations.AddField(
            model_name='terpene',
            name='translation_error',
            field=models.TextField(blank=True, help_text='Error message if translation failed', null=True),
        ),
        migrations.AddField(
            model_name='terpene',
            name='translation_source_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of English content when last translated', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='terpene',
            name='translation_status',
            field=models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('outdated', 'Outdated'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
