# Generated by Django 4.2.16 on 2025-10-09

from django.db import migrations


def migrate_spanish_content(apps, schema_editor):
    """
    Migrate existing content to appropriate language fields:
    - Strains, Articles, Terpenes: Spanish content → _es fields (leave _en empty for translation)
    - Taxonomy (Feelings, etc.): English (DB) → _en, Spanish (from dict) → _es
    """
    Strain = apps.get_model('strains', 'Strain')
    Article = apps.get_model('strains', 'Article')
    Terpene = apps.get_model('strains', 'Terpene')
    Feeling = apps.get_model('strains', 'Feeling')
    Negative = apps.get_model('strains', 'Negative')
    HelpsWith = apps.get_model('strains', 'HelpsWith')
    Flavor = apps.get_model('strains', 'Flavor')

    # Translation dictionaries (from localizations.py)
    feelings_translation = {
        'Sleepy': 'Soñoliento', 'Hungry': 'Hambriento', 'Relaxed': 'Relajación',
        'Energetic': 'Enérgico', 'Uplifted': 'Elevado', 'Focused': 'Enfoque',
        'Giggly': 'Risitas', 'Talkative': 'Hablador', 'Creative': 'Creativo',
        'Happy': 'Feliz', 'Euphoric': 'Eufórico', 'Aroused': 'Excitado', 'Tingly': 'Hormigueo'
    }

    helps_with_translation = {
        'ADD/ADHD': 'TDA/TDAH', "Alzheimer's": 'Alzheimer', 'Anorexia': 'Anorexia',
        'Anxiety': 'Ansiedad', 'Arthritis': 'Artritis', 'Asthma': 'Asma',
        'Bipolar disorder': 'Trastorno bipolar', 'Cachexia': 'Caquexia', 'Cancer': 'Cáncer',
        'Cramps': 'Calambres', "Crohn's disease": 'Enfermedad de Crohn', 'Depression': 'Depresión',
        'Epilepsy': 'Epilepsia', 'Eye pressure': 'Presión ocular', 'Fatigue': 'Fatiga',
        'Fibromyalgia': 'Fibromialgia', 'Gastrointestinal disorder': 'Trastorno gastrointestinal',
        'Glaucoma': 'Glaucoma', 'Headaches': 'Dolores de cabeza', 'HIV/AIDS': 'VIH/SIDA',
        'Hypertension': 'Hipertensión', 'Inflammation': 'Inflamación', 'Insomnia': 'Insomnio',
        'Lack of appetite': 'Pérdida de apetito', 'Migraines': 'Migrañas',
        'Multiple sclerosis': 'Esclerosis múltiple', 'Muscle spasms': 'Espasmos musculares',
        'Muscular dystrophy': 'Distrofia muscular', 'Nausea': 'Náuseas', 'Pain': 'Dolor',
        "Parkinson's": 'Parkinson', 'Phantom limb pain': 'Dolor de miembro fantasma',
        'PMS': 'PMS', 'PTSD': 'TEPT', 'Seizures': 'Convulsiones', 'Spasticity': 'Espasticidad',
        'Spinal cord injury': 'Lesión medular', 'Stress': 'Estrés', 'Tinnitus': 'Acúfenos',
    }

    flavors_translation = {
        'blueberry': 'Arándanos', 'berry': 'Bayas', 'sweet': 'Dulce', 'orange': 'Naranja',
        'citrus': 'Cítricos', 'peach': 'Melocotón', 'lavender': 'Lavanda', 'grape': 'Uva',
        'vanilla': 'Vainilla', 'pineapple': 'Piña', 'mango': 'Mango', 'strawberry': 'Fresa',
        'diesel': 'Diesel', 'tea': 'Té', 'pine': 'Pino', 'lemon': 'Limón',
        'spicy/herbal': 'Especias/Hierbas', 'pungent': 'Picante', 'skunk': 'Zorrilla',
        'ammonia': 'Amoníaco', 'pepper': 'Pimienta', 'apricot': 'Albaricoque',
        'tree fruit': 'Frutas de árbol', 'coffee': 'Café', 'earthy': 'Terroso',
        'mint': 'Menta', 'butter': 'Manteca', 'tobacco': 'Tabaco', 'apple': 'Manzana',
        'cheese': 'Queso', 'grapefruit': 'Pomelo', 'woody': 'Maderoso', 'honey': 'Miel',
        'tropical': 'Tropical', 'violet': 'Violeta', 'menthol': 'Mentol', 'sage': 'Salvia',
        'chemical': 'Químico', 'blue cheese': 'Queso azul', 'chestnut': 'Castaño',
        'flowery': 'Florido', 'lime': 'Lima', 'nutty': 'Nueces', 'pear': 'Pera',
        'plum': 'Ciruela', 'rose': 'Rosa', 'tar': 'Alquitrán',
    }

    negatives_translation = {
        'Dry mouth': 'Boca seca', 'Dry eyes': 'Ojos secos', 'Dizzy': 'Mareado',
        'Anxious': 'Ansioso', 'Paranoid': 'Paranoico', 'Headache': 'Cefalea',
    }

    # Migrate Strains: Spanish content → _es fields
    for strain in Strain.objects.all():
        strain.title_es = strain.title
        strain.description_es = strain.description
        strain.text_content_es = strain.text_content
        strain.keywords_es = strain.keywords
        strain.img_alt_text_es = strain.img_alt_text
        # Leave _en fields as null - will be filled by AWS Lambda
        strain.title_en = None
        strain.description_en = None
        strain.text_content_en = None
        strain.keywords_en = None
        strain.img_alt_text_en = None
        strain.translation_status = 'pending'
        strain.save()

    # Migrate Articles: Spanish content → _es fields
    for article in Article.objects.all():
        article.title_es = article.title
        article.description_es = article.description
        article.text_content_es = article.text_content
        article.keywords_es = article.keywords
        # Leave _en fields as null - will be filled by AWS Lambda
        article.title_en = None
        article.description_en = None
        article.text_content_en = None
        article.keywords_en = None
        article.translation_status = 'pending'
        article.save()

    # Migrate Terpenes: Spanish description → _es field
    for terpene in Terpene.objects.all():
        terpene.description_es = terpene.description
        terpene.description_en = None  # Will be filled by AWS Lambda
        terpene.translation_status = 'pending'
        terpene.save()

    # Migrate taxonomy models: English (DB) → _en, Spanish (dict) → _es
    for feeling in Feeling.objects.all():
        feeling.name_en = feeling.name  # English from DB
        feeling.name_es = feelings_translation.get(feeling.name, feeling.name)
        feeling.save()

    for negative in Negative.objects.all():
        negative.name_en = negative.name  # English from DB
        negative.name_es = negatives_translation.get(negative.name, negative.name)
        negative.save()

    for helps in HelpsWith.objects.all():
        helps.name_en = helps.name  # English from DB
        helps.name_es = helps_with_translation.get(helps.name, helps.name)
        helps.save()

    for flavor in Flavor.objects.all():
        flavor.name_en = flavor.name  # English from DB
        flavor.name_es = flavors_translation.get(flavor.name, flavor.name)
        flavor.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - clear all translated fields"""
    Strain = apps.get_model('strains', 'Strain')
    Article = apps.get_model('strains', 'Article')
    Terpene = apps.get_model('strains', 'Terpene')
    Feeling = apps.get_model('strains', 'Feeling')
    Negative = apps.get_model('strains', 'Negative')
    HelpsWith = apps.get_model('strains', 'HelpsWith')
    Flavor = apps.get_model('strains', 'Flavor')

    Strain.objects.all().update(
        title_en=None, title_es=None,
        description_en=None, description_es=None,
        text_content_en=None, text_content_es=None,
        keywords_en=None, keywords_es=None,
        img_alt_text_en=None, img_alt_text_es=None,
        translation_status='pending'
    )
    Article.objects.all().update(
        title_en=None, title_es=None,
        description_en=None, description_es=None,
        text_content_en=None, text_content_es=None,
        keywords_en=None, keywords_es=None,
        translation_status='pending'
    )
    Terpene.objects.all().update(
        description_en=None, description_es=None,
        translation_status='pending'
    )
    Feeling.objects.all().update(name_en=None, name_es=None)
    Negative.objects.all().update(name_en=None, name_es=None)
    HelpsWith.objects.all().update(name_en=None, name_es=None)
    Flavor.objects.all().update(name_en=None, name_es=None)


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0015_article_description_en_article_description_es_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_spanish_content, reverse_migration),
    ]
