# Generated by Django 4.2.16 on 2026-02-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0017_alter_strain_rating_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="strain",
            name="parents",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="strains.strain"
            ),
        ),
    ]
