# Generated by Django 4.2.27 on 2026-02-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0018_strain_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='review_summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='review_summary_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
