# Generated by Django 4.2.16 on 2026-03-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0019_strain_review_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="terpene",
            name="name_en",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="terpene",
            name="name_es",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
