# Generated by Django 4.2 on 2026-04-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strains', '0021_populate_terpene_name_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='strains.strain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_strains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='favoritestrain',
            constraint=models.UniqueConstraint(fields=('user', 'strain'), name='unique_favorite_strain'),
        ),
    ]
