# Generated by Django 4.2 on 2026-04-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strains', '0022_favoritestrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrainComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('reaction', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('moderation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='strains.strain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strain_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='straincomment',
            constraint=models.UniqueConstraint(fields=('user', 'strain'), name='unique_strain_comment'),
        ),
    ]
