# Generated by Django 4.2 on 2023-04-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Uplifted', 'Uplifted'), ('Euphoric', 'Euphoric'), ('Energetic', 'Energetic')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Butter', 'Butter'), ('Vanilla', 'Vanilla'), ('Citrus', 'Citrus')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpsWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Anxiety', 'Anxiety'), ('Depression', 'Depression'), ('Stress', 'Stress')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Negative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dizzy', 'Dizzy'), ('Anxious', 'Anxious'), ('Paranoid', 'Paranoid')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cbd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cbg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Sativa', 'Sativa'), ('Indica', 'Indica')], max_length=10)),
                ('text_content', models.TextField()),
                ('description', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('feelings', models.ManyToManyField(to='strains.feeling')),
                ('flavors', models.ManyToManyField(to='strains.flavor')),
                ('helps_with', models.ManyToManyField(to='strains.helpswith')),
                ('negatives', models.ManyToManyField(to='strains.negative')),
            ],
        ),
    ]
