# Generated by Django 4.2 on 2023-04-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='cbd',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='cbg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
