# Generated by Django 4.2 on 2023-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0003_strain_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='img_url',
        ),
        migrations.AddField(
            model_name='strain',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='strains/'),
        ),
    ]
