feelings_translation = {
    'Sleepy': 'Soñoliento',
    'Hungry': 'Hambriento',
    'Relaxed': 'Relajación',
    'Energetic': 'Enérgico',
    'Uplifted': 'Elevado',
    'Focused': 'Enfoque',
    'Giggly': 'Risitas',
    'Talkative': 'Hablador',
    'Creative': 'Creativo',
    'Happy': 'Feliz',
    'Euphoric': 'Eufórico',
    'Aroused': 'Excitado',
    'Tingly': 'Hormigueo'
}

helps_with_translation = {
    'ADD/ADHD': 'TDA/TDAH',
    'Alzheimer\'s': 'Alzheimer',
    'Anorexia': 'Anorexia',
    'Anxiety': 'Ansiedad',
    'Arthritis': 'Artritis',
    'Asthma': 'Asma',
    'Bipolar disorder': 'Trastorno bipolar',
    'Cachexia': 'Caquexia',
    'Cancer': 'Cáncer',
    'Cramps': 'Calambres',
    'Crohn\'s disease': 'Enfermedad de Crohn',
    'Depression': 'Depresión',
    'Epilepsy': 'Epilepsia',
    'Eye pressure': 'Presión ocular',
    'Fatigue': 'Fatiga',
    'Fibromyalgia': 'Fibromialgia',
    'Gastrointestinal disorder': 'Trastorno gastrointestinal',
    'Glaucoma': 'Glaucoma',
    'Headaches': 'Dolores de cabeza',
    'HIV/AIDS': 'VIH/SIDA',
    'Hypertension': 'Hipertensión',
    'Inflammation': 'Inflamación',
    'Insomnia': 'Insomnio',
    'Lack of appetite': 'Pérdida de apetito',
    'Migraines': 'Migrañas',
    'Multiple sclerosis': 'Esclerosis múltiple',
    'Muscle spasms': 'Espasmos musculares',
    'Muscular dystrophy': 'Distrofia muscular',
    'Nausea': 'Náuseas',
    'Pain': 'Dolor',
    'Parkinson\'s': 'Parkinson',
    'Phantom limb pain': 'Dolor de miembro fantasma',
    'PMS': 'PMS',
    'PTSD': 'TEPT',
    'Seizures': 'Convulsiones',
    'Spasticity': 'Espasticidad',
    'Spinal cord injury': 'Lesión medular',
    'Stress': 'Estrés',
    'Tinnitus': 'Acúfenos',
}


flavors_translation = {
    'blueberry': 'Arándanos',
    'berry': 'Bayas',
    'sweet': 'Dulce',
    'orange': 'Naranja',
    'citrus': 'Cítricos',
    'peach': 'Melocotón',
    'lavender': 'Lavanda',
    'grape': 'Uva',
    'vanilla': 'Vainilla',
    'pineapple': 'Piña',
    'mango': 'Mango',
    'strawberry': 'Fresa',
    'diesel': 'Diesel',
    'tea': 'Té',
    'pine': 'Pino',
    'lemon': 'Limón',
    'spicy/herbal': 'Especias/Hierbas',
    'pungent': 'Picante',
    'skunk': 'Zorrilla',
    'ammonia': 'Amoníaco',
    'pepper': 'Pimienta',
    'apricot': 'Albaricoque',
    'tree fruit': 'Frutas de árbol',
    'coffee': 'Café',
    'earthy': 'Terroso',
    'mint': 'Menta',
    'butter': 'Manteca',
    'tobacco': 'Tabaco',
    'apple': 'Manzana',
    'cheese': 'Queso',
    'grapefruit': 'Pomelo',
    'woody': 'Maderoso',
    'honey': 'Miel',
    'tropical': 'Tropical',
    'violet': 'Violeta',
    'menthol': 'Mentol',
    'sage': 'Salvia',
    'chemical': 'Químico',
    'blue cheese': 'Queso azul',
    'chestnut': 'Castaño',
    'flowery': 'Florido',
    'lime': 'Lima',
    'nutty': 'Nueces',
    'pear': 'Pera',
    'plum': 'Ciruela',
    'rose': 'Rosa',
    'tar': 'Alquitrán',
}


negatives_translator = {
    'Dry mouth': 'Boca seca',
    'Dry eyes':	'Ojos secos',
    'Dizzy': 'Mareado',
    'Anxious': 'Ansioso',
    'Paranoid':	'Paranoico',
    'Headache':	'Cefalea',
}

